"""Service rewrites batch 3: drain-replacement through whole-house-repiping."""

def register(svc):

    svc("drain-replacement",
        "Drain Line Replacement in Chicago, IL",
        "Drain line replacement in Chicago — corroded, cracked, or collapsed drain pipes replaced with modern materials. Call 833-758-6911.",
        '<h2>Drain Line Replacement</h2>'
        '<p>When a drain line is cracked, corroded, collapsed, or has repeated blockages that cleaning can\'t solve, replacement is the permanent fix. We replace interior and exterior drain lines using modern PVC and ABS materials that outlast the originals by decades.</p>'
        '<h2>Signs Your Drain Line Needs Replacement</h2>'
        '<ul>'
        '<li><strong>Recurring clogs</strong> in the same line despite professional cleaning</li>'
        '<li><strong>Slow drainage</strong> that doesn\'t improve after snaking</li>'
        '<li><strong>Sewage odor</strong> from the drain even when it\'s not clogged</li>'
        '<li><strong>Visible corrosion</strong> on exposed cast iron or galvanized drain pipes</li>'
        '<li><strong>Water damage</strong> on ceilings or walls below drain lines</li>'
        '<li><strong>Camera inspection</strong> showing cracks, bellies, or collapse</li>'
        '</ul>'
        '<h2>What We Replace</h2>'
        '<ul>'
        '<li><strong>Kitchen and bathroom drain lines:</strong> From fixture to main stack</li>'
        '<li><strong>Main drain stack:</strong> The vertical pipe connecting upper floors to the sewer</li>'
        '<li><strong>Underground drains:</strong> Below-slab drain lines in basements</li>'
        '<li><strong>Laundry and utility drains:</strong> Corroded galvanized or cast iron lines</li>'
        '</ul>'
        '<h2>Typical Drain Replacement Costs</h2>'
        '<ul>'
        '<li><strong>Single drain line (fixture to stack):</strong> $500–$2,000</li>'
        '<li><strong>Main drain stack replacement:</strong> $2,000–$6,000</li>'
        '<li><strong>Below-slab drain replacement:</strong> $2,500–$8,000+ (includes concrete cutting and restoration)</li>'
        '<li><strong>Whole-house drain replacement:</strong> $5,000–$15,000+</li>'
        '</ul>'
        '<p>Costs vary based on pipe material, access, length, and whether concrete or finished walls need to be opened. We restore all access points when the work is complete.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How do I know if my drains need replacement vs. just cleaning?</h3>'
        '<p>If professional cleaning solves the problem and it stays solved for a year or more, cleaning is enough. If the same line clogs every few months, or a camera shows structural damage, replacement is the long-term answer.</p>'
        '<h3>What material do you use for replacement drains?</h3>'
        '<p>PVC for most residential drain replacements. It\'s durable, smooth (resists buildup), lightweight, and code-compliant. For below-slab work, we use Schedule 40 PVC. Cast iron is sometimes used in multi-unit buildings for noise reduction.</p>'
        '<h3>Do you need to cut into my walls or floor?</h3>'
        '<p>It depends on where the damaged pipe is. Exposed basement pipes are straightforward. Pipes inside walls or under concrete slabs require opening access. We minimize the opening and restore it after the work.</p>'
        '<h3>How long does drain replacement take?</h3>'
        '<p>A single drain line: half a day to a full day. Main stack replacement: 1–2 days. Below-slab work: 1–3 days including concrete cutting and restoration.</p>'
        '<h3>Can you replace just the damaged section?</h3>'
        '<p>Yes. If the damage is isolated, a spot repair saves money. If the entire line is deteriorated, full replacement prevents future failures and repeated repairs.</p>'
    )

    svc("water-heater-repair",
        "Water Heater Repair in Chicago, IL",
        "Water heater repair in Chicago — no hot water, leaking tanks, pilot light issues, and more. Licensed plumbers, 24/7. Call 833-758-6911.",
        '<h2>Water Heater Repair</h2>'
        '<p>No hot water in a Chicago winter is an emergency. We diagnose and repair gas and electric water heaters — tank and tankless — throughout Chicagoland. Most repairs can be done the same day, and we carry the common parts on our trucks.</p>'
        '<h2>Common Water Heater Problems</h2>'
        '<ul>'
        '<li><strong>No hot water:</strong> Dead pilot light, failed thermocouple, bad heating element, or tripped reset</li>'
        '<li><strong>Not enough hot water:</strong> Sediment buildup, undersized tank, or a failing dip tube</li>'
        '<li><strong>Water too hot:</strong> Thermostat set too high or a malfunctioning thermostat</li>'
        '<li><strong>Leaking tank:</strong> Could be a relief valve, a fitting, or the tank itself (tank corrosion = replacement)</li>'
        '<li><strong>Strange noises:</strong> Popping or rumbling usually means sediment buildup on the bottom of the tank</li>'
        '<li><strong>Rusty or smelly water:</strong> Corroded anode rod or bacteria in the tank</li>'
        '</ul>'
        '<h2>Typical Water Heater Repair Costs</h2>'
        '<ul>'
        '<li><strong>Thermocouple replacement:</strong> $100–$200</li>'
        '<li><strong>Heating element replacement (electric):</strong> $150–$300</li>'
        '<li><strong>Thermostat replacement:</strong> $150–$300</li>'
        '<li><strong>T&amp;P relief valve replacement:</strong> $100–$250</li>'
        '<li><strong>Anode rod replacement:</strong> $150–$300</li>'
        '<li><strong>Dip tube replacement:</strong> $150–$300</li>'
        '<li><strong>Tank flush (sediment removal):</strong> $100–$200</li>'
        '</ul>'
        '<p>If your water heater is over 10 years old and the tank is leaking, replacement is usually more practical than repair. We\'ll give you an honest assessment.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long do water heaters last?</h3>'
        '<p>Tank water heaters typically last 8–12 years. Tankless units can last 15–20 years with proper maintenance. Hard water (common in Chicago suburbs) shortens lifespan due to mineral buildup.</p>'
        '<h3>Why is my water heater making popping sounds?</h3>'
        '<p>Sediment has settled on the bottom of the tank. When the burner heats the water, it creates steam bubbles under the sediment layer. A tank flush can solve this. If it\'s been years since a flush, the sediment may be hardite and the tank may need replacement.</p>'
        '<h3>Can a water heater be repaired if it\'s leaking from the bottom?</h3>'
        '<p>If the leak is from the drain valve or a fitting, yes. If the tank itself is leaking (internal corrosion), no — the tank can\'t be patched. Replacement is the only option.</p>'
        '<h3>Should I repair or replace my water heater?</h3>'
        '<p>If the unit is under 8 years old and the repair is under $400, repair makes sense. If it\'s over 10, or the tank is corroding, invest in a new one. You\'ll get better efficiency and a fresh warranty.</p>'
        '<h3>Do you repair both gas and electric water heaters?</h3>'
        '<p>Yes. We work on all major brands — Rheem, AO Smith, Bradford White, State, and others. Gas and electric, tank and tankless.</p>'
    )

    svc("water-heater-installation",
        "Water Heater Installation in Chicago, IL",
        "Water heater installation in Chicago — tank and tankless units, gas and electric. Licensed plumbers with same-day service. Call 833-758-6911.",
        '<h2>Water Heater Installation</h2>'
        '<p>Whether your old water heater just died or you\'re upgrading to a more efficient unit, we handle the full installation — removal of the old unit, setting the new one, connecting gas or electric, plumbing the water lines, and making sure everything is up to code.</p>'
        '<h2>Types of Water Heaters We Install</h2>'
        '<ul>'
        '<li><strong>Standard tank (gas):</strong> The most common type in Chicago homes. 40–50 gallon tanks for most families.</li>'
        '<li><strong>Standard tank (electric):</strong> Good option where gas isn\'t available. Lower upfront cost, higher operating cost.</li>'
        '<li><strong>Tankless (gas):</strong> Endless hot water, smaller footprint, higher efficiency. Higher upfront cost.</li>'
        '<li><strong>Tankless (electric):</strong> Point-of-use units for single fixtures or small whole-house units.</li>'
        '<li><strong>High-efficiency condensing:</strong> 90%+ efficiency, vents through PVC instead of metal flue.</li>'
        '</ul>'
        '<h2>What Installation Includes</h2>'
        '<ul>'
        '<li>Disconnection and removal of old water heater</li>'
        '<li>New water heater set in place and leveled</li>'
        '<li>Gas line or electrical connection</li>'
        '<li>Water supply and discharge piping</li>'
        '<li>T&amp;P relief valve and discharge pipe</li>'
        '<li>Expansion tank (if required by code)</li>'
        '<li>Venting (gas units)</li>'
        '<li>Testing and temperature adjustment</li>'
        '</ul>'
        '<h2>Typical Water Heater Installation Costs</h2>'
        '<ul>'
        '<li><strong>Standard 40–50 gal tank (gas):</strong> $800–$1,800 including unit and labor</li>'
        '<li><strong>Standard 40–50 gal tank (electric):</strong> $700–$1,500 including unit and labor</li>'
        '<li><strong>Tankless (gas):</strong> $2,500–$5,000 including unit, venting, and gas line upgrades</li>'
        '<li><strong>High-efficiency condensing:</strong> $1,500–$3,000 including unit and labor</li>'
        '<li><strong>Old unit disposal:</strong> Usually included in the installation price</li>'
        '</ul>'
        '<p>Tankless installations cost more upfront but save 20–30% on water heating energy costs. We help you weigh the investment based on your household size and hot water usage.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long does water heater installation take?</h3>'
        '<p>A standard tank swap takes 2–4 hours. Tankless installations take 4–8 hours due to additional venting and gas line work. If we\'re converting from tank to tankless, it may require a full day.</p>'
        '<h3>What size water heater do I need?</h3>'
        '<p>For a family of 2–3: a 40-gallon tank or a tankless unit rated for 2–3 simultaneous fixtures. Family of 4–5: a 50-gallon tank or a larger tankless unit. We\'ll size it based on your household and usage patterns.</p>'
        '<h3>Do I need a permit for water heater installation in Chicago?</h3>'
        '<p>The City of Chicago requires a permit for water heater replacement. We pull the permit and schedule the inspection as part of the job. Suburban requirements vary — we know the codes for each municipality.</p>'
        '<h3>Should I switch from tank to tankless?</h3>'
        '<p>Tankless is worth considering if you want endless hot water, have limited space, or plan to stay in the home 10+ years to recoup the higher upfront cost. For homes with high simultaneous demand, a large tank or multiple tankless units may be needed.</p>'
        '<h3>Can I install a water heater myself?</h3>'
        '<p>We don\'t recommend it. Gas water heaters involve gas connections, venting, and combustion safety. Electric units involve high-amperage wiring. Both require code-compliant installation. Improper installation can void the warranty and create safety hazards.</p>'
    )

    svc("tankless-water-heater-repair",
        "Tankless Water Heater Repair in Chicago, IL",
        "Tankless water heater repair in Chicago — error codes, no hot water, fluctuating temps. Licensed plumbers. Call 833-758-6911.",
        '<h2>Tankless Water Heater Repair</h2>'
        '<p>Tankless water heaters are reliable, but they\'re not maintenance-free. When they throw an error code, produce inconsistent temperatures, or stop heating altogether, you need a plumber who understands how these units work. We repair all major tankless brands throughout Chicagoland.</p>'
        '<h2>Common Tankless Problems</h2>'
        '<ul>'
        '<li><strong>Error codes:</strong> Each brand has specific codes — ignition failure, flame loss, flow sensor issues, exhaust blockage</li>'
        '<li><strong>No hot water:</strong> Could be ignition failure, gas supply issue, or frozen condensate line (winter)</li>'
        '<li><strong>Fluctuating temperatures:</strong> Often a flow rate issue, dirty heat exchanger, or crossover in the plumbing</li>'
        '<li><strong>Mineral scale buildup:</strong> Chicago\'s hard water deposits calcium on the heat exchanger, reducing efficiency</li>'
        '<li><strong>Low flow rate:</strong> Clogged inlet filter, scaled heat exchanger, or undersized unit for demand</li>'
        '</ul>'
        '<h2>Maintenance Matters</h2>'
        '<p>Tankless water heaters should be flushed with descaling solution annually — more often in areas with hard water. This removes mineral scale from the heat exchanger and keeps the unit running efficiently. Skipping maintenance is the #1 cause of premature tankless failure.</p>'
        '<h2>Typical Tankless Repair Costs</h2>'
        '<ul>'
        '<li><strong>Diagnostic + minor repair:</strong> $150–$350</li>'
        '<li><strong>Descaling/flush service:</strong> $150–$300</li>'
        '<li><strong>Ignition or flame rod replacement:</strong> $200–$400</li>'
        '<li><strong>Flow sensor replacement:</strong> $200–$400</li>'
        '<li><strong>Heat exchanger replacement:</strong> $500–$1,500 (often worth considering a new unit)</li>'
        '</ul>'
        '<p>If the heat exchanger fails outside of warranty, a new unit is often more cost-effective than the repair. We\'ll give you an honest comparison.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Why does my tankless water heater fluctuate between hot and cold?</h3>'
        '<p>This "cold water sandwich" effect happens when the unit cycles on and off during intermittent use. It can also indicate a dirty heat exchanger, crossover from another fixture, or a flow rate below the unit\'s activation threshold.</p>'
        '<h3>How often should a tankless water heater be flushed?</h3>'
        '<p>Annually for most homes. In areas with very hard water (common in Chicago suburbs), every 6 months. Regular flushing extends the unit\'s life and maintains efficiency.</p>'
        '<h3>What brands do you service?</h3>'
        '<p>We repair Rinnai, Navien, Noritz, Takagi, Rheem, Bosch, and other major brands. We carry common parts and can order brand-specific components quickly.</p>'
        '<h3>My tankless shows an error code — what should I do?</h3>'
        '<p>Note the error code and call us. Don\'t try to reset the unit repeatedly — some codes indicate safety issues. We\'ll diagnose the specific code and make the repair.</p>'
        '<h3>Is it worth repairing an old tankless water heater?</h3>'
        '<p>Tankless units last 15–20 years. If yours is under 10 and the repair is reasonable, fix it. Over 15 with a major component failure, replacement makes more sense.</p>'
    )

    svc("tankless-water-heater-installation",
        "Tankless Water Heater Installation in Chicago, IL",
        "Tankless water heater installation in Chicago — endless hot water, energy savings. Gas and electric units. Call 833-758-6911.",
        '<h2>Tankless Water Heater Installation</h2>'
        '<p>Tankless water heaters heat water on demand — no stored tank, no running out of hot water, and 20–30% less energy used compared to a standard tank. We install gas and electric tankless units in homes across Chicagoland, including conversions from traditional tank heaters.</p>'
        '<h2>Why Go Tankless?</h2>'
        '<ul>'
        '<li><strong>Endless hot water:</strong> Heats water as it flows — no waiting for a tank to recover</li>'
        '<li><strong>Energy savings:</strong> Only heats water when you need it. 20–30% more efficient than tank units.</li>'
        '<li><strong>Space savings:</strong> Wall-mounted units free up floor space</li>'
        '<li><strong>Longer lifespan:</strong> 15–20 years vs. 8–12 for tank heaters</li>'
        '<li><strong>Cleaner water:</strong> No standing water in a corroding tank</li>'
        '</ul>'
        '<h2>What Installation Involves</h2>'
        '<ul>'
        '<li>Removing old water heater (if converting)</li>'
        '<li>Mounting the tankless unit on the wall</li>'
        '<li>Upgrading gas line (tankless units often need a larger gas supply)</li>'
        '<li>Installing stainless steel venting (gas units)</li>'
        '<li>Connecting water supply and discharge lines</li>'
        '<li>Electrical connection for controls</li>'
        '<li>Condensate drain (condensing models)</li>'
        '<li>System testing and temperature programming</li>'
        '</ul>'
        '<h2>Typical Installation Costs</h2>'
        '<ul>'
        '<li><strong>Gas tankless (whole-house):</strong> $2,500–$5,000 including unit, venting, gas line</li>'
        '<li><strong>Electric tankless (whole-house):</strong> $1,500–$3,500 including unit and electrical work</li>'
        '<li><strong>Electric tankless (point-of-use):</strong> $300–$800 per unit</li>'
        '<li><strong>Tank-to-tankless conversion:</strong> Add $500–$1,500 for gas line upgrade and new venting</li>'
        '</ul>'
        '<p>The higher upfront cost is offset by lower monthly energy bills and a longer unit lifespan. Most homeowners see payback within 5–7 years.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Can my home handle a tankless water heater?</h3>'
        '<p>Most homes can. Gas tankless units may need a larger gas line and dedicated venting. Electric units may need a panel upgrade. We assess your home\'s infrastructure before recommending a unit.</p>'
        '<h3>What size tankless unit do I need?</h3>'
        '<p>Size is based on flow rate (GPM) and temperature rise. In Chicago, where incoming water is cold (around 45°F in winter), you need more heating capacity. A family of 4 typically needs a unit rated at 8–10 GPM for gas.</p>'
        '<h3>Will I really never run out of hot water?</h3>'
        '<p>You won\'t run out, but you can exceed the unit\'s capacity if too many fixtures run simultaneously. Proper sizing prevents this. For large homes, we may recommend two units or a recirculation system.</p>'
        '<h3>Do tankless water heaters work in Chicago winters?</h3>'
        '<p>Yes. The unit works harder because incoming water is colder, which slightly reduces flow capacity. We size the unit for Chicago\'s winter water temperatures, not just summer.</p>'
        '<h3>How long does tankless installation take?</h3>'
        '<p>A straightforward installation takes 4–6 hours. Conversions from tank to tankless take 6–8 hours due to gas line and venting modifications. We complete most installations in a single day.</p>'
    )

    svc("backflow-testing-installation",
        "Backflow Testing & Installation in Chicago, IL",
        "Backflow preventer testing and installation in Chicago — annual certification, RPZ and DCV devices. Licensed plumbers. Call 833-758-6911.",
        '<h2>Backflow Testing &amp; Installation</h2>'
        '<p>Backflow preventers keep contaminated water from flowing backward into the clean water supply. Illinois requires annual testing of these devices, and Chicago\'s water department enforces it. We install, test, and certify backflow prevention devices for residential and commercial properties.</p>'
        '<h2>Why Backflow Prevention Matters</h2>'
        '<p>Without a working backflow preventer, a drop in water pressure can pull contaminated water — from irrigation systems, boilers, fire sprinklers, or commercial equipment — back into the potable water supply. It\'s a serious health hazard and a code violation.</p>'
        '<h2>Our Backflow Services</h2>'
        '<ul>'
        '<li><strong>Annual testing:</strong> Required by Illinois code. We test, certify, and file the results.</li>'
        '<li><strong>New installation:</strong> RPZ (Reduced Pressure Zone), DCV (Double Check Valve), and PVB (Pressure Vacuum Breaker) devices</li>'
        '<li><strong>Repair and rebuild:</strong> Replacing internal components when a device fails testing</li>'
        '<li><strong>Replacement:</strong> When a device is too old or damaged to repair</li>'
        '</ul>'
        '<h2>Typical Backflow Service Costs</h2>'
        '<ul>'
        '<li><strong>Annual backflow test (per device):</strong> $75–$200</li>'
        '<li><strong>Backflow repair/rebuild:</strong> $150–$500 depending on device type</li>'
        '<li><strong>New RPZ installation:</strong> $800–$2,500 depending on size and location</li>'
        '<li><strong>New DCV installation:</strong> $500–$1,500</li>'
        '</ul>'
        '<p>Annual testing is an ongoing requirement. We send reminders and can set up a recurring service schedule.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Do I need a backflow preventer?</h3>'
        '<p>If you have a sprinkler/irrigation system, boiler, fire suppression system, or any connection to non-potable water, yes. Commercial properties almost always require them. Residential requirements vary by municipality.</p>'
        '<h3>How often does a backflow preventer need testing?</h3>'
        '<p>Annually. Illinois requires certified testing every year, and results must be filed with the local water authority. Failure to test can result in fines or water service disconnection.</p>'
        '<h3>What happens if my backflow preventer fails the test?</h3>'
        '<p>We repair or rebuild it on the spot if possible. Common issues are worn check valves or relief valve seats. After repair, we re-test and certify. If the device is beyond repair, we replace it.</p>'
        '<h3>Who is certified to test backflow preventers?</h3>'
        '<p>Only plumbers with a CCCDI (Cross-Connection Control Device Inspector) certification can test and certify backflow devices in Illinois. Our testers hold current certification.</p>'
        '<h3>Can I get fined for not testing my backflow preventer?</h3>'
        '<p>Yes. The City of Chicago and suburban water departments issue violation notices and fines for non-compliance. In some cases, they can shut off water service until the device is tested and certified.</p>'
    )

    svc("whole-house-repiping",
        "Whole House Repiping in Chicago, IL",
        "Whole house repiping in Chicago — replace old galvanized, lead, or polybutylene pipes with copper or PEX. Call 833-758-6911.",
        '<h2>Whole House Repiping</h2>'
        '<p>If your home still has galvanized steel, lead, or polybutylene water lines, it\'s time to repipe. Galvanized pipes corrode from the inside, restricting flow and turning water brown. Lead pipes are a health hazard. Polybutylene is prone to sudden failure. We replace old piping throughout your home with modern copper or PEX — restoring full water pressure and clean water to every fixture.</p>'
        '<h2>Signs You Need Repiping</h2>'
        '<ul>'
        '<li><strong>Low water pressure:</strong> Throughout the house, not just one fixture. Corroded pipes restrict flow.</li>'
        '<li><strong>Discolored water:</strong> Brown, yellow, or rusty water from hot and cold taps.</li>'
        '<li><strong>Frequent leaks:</strong> Multiple pinhole leaks in different locations — the whole system is failing.</li>'
        '<li><strong>Galvanized pipes:</strong> Common in Chicago homes built before 1960. Past their 40–60 year lifespan.</li>'
        '<li><strong>Lead pipes:</strong> Found in some pre-1950s Chicago homes. Should be replaced for health reasons.</li>'
        '<li><strong>Visible corrosion:</strong> Green, white, or orange deposits on exposed pipes.</li>'
        '</ul>'
        '<h2>Pipe Material Options</h2>'
        '<ul>'
        '<li><strong>Copper:</strong> Industry standard. Durable, code-compliant everywhere, 50+ year lifespan. Higher material cost.</li>'
        '<li><strong>PEX (cross-linked polyethylene):</strong> Flexible, freeze-resistant, faster to install. Lower material cost. Accepted by most Chicago-area codes.</li>'
        '<li><strong>Copper + PEX hybrid:</strong> Copper for exposed runs, PEX for in-wall and in-floor runs. Balances cost and durability.</li>'
        '</ul>'
        '<h2>Typical Whole-House Repiping Costs</h2>'
        '<ul>'
        '<li><strong>Small home (1 bath, 1,000 sq ft):</strong> $4,000–$7,000</li>'
        '<li><strong>Average home (2 bath, 1,500 sq ft):</strong> $6,000–$12,000</li>'
        '<li><strong>Large home (3+ bath, 2,500+ sq ft):</strong> $10,000–$18,000+</li>'
        '<li><strong>Drywall/plaster repair (patching access holes):</strong> $500–$2,000+</li>'
        '</ul>'
        '<p>PEX repiping is typically 20–30% less than copper due to lower material cost and faster installation. We provide both options in our quote.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long does whole-house repiping take?</h3>'
        '<p>Most homes take 2–4 days. Day one involves running new pipes. Day two connects all fixtures. We minimize time without water — typically only a few hours during the cutover.</p>'
        '<h3>Do I need to move out during repiping?</h3>'
        '<p>No. We work room by room and keep disruption manageable. You\'ll be without water for a few hours during the main connections, but we plan around your schedule.</p>'
        '<h3>Will repiping damage my walls?</h3>'
        '<p>We need small access holes in walls and ceilings to run new pipes. We keep them as small as possible and can patch or arrange for a drywall contractor. In homes with accessible basements and attics, wall access is minimal.</p>'
        '<h3>Should I choose copper or PEX?</h3>'
        '<p>Both are excellent. Copper is proven and lasts 50+ years but costs more. PEX is flexible (fewer fittings, fewer potential leak points), freeze-resistant, and more affordable. In Chicago, most homeowners choose PEX for the savings and performance.</p>'
        '<h3>Will repiping improve my water pressure?</h3>'
        '<p>If low pressure is caused by corroded pipes (which it usually is in older homes), yes — dramatically. New pipes restore the full flow your fixtures were designed for.</p>'
    )
