"""Service rewrites batch 2: faucet-repair through drain-cleaning."""

def register(svc):

    svc("faucet-repair",
        "Faucet Repair & Installation in Chicago, IL",
        "Faucet repair and installation in Chicago — dripping faucets, new installs, kitchen and bath. Licensed plumbers. Call 833-758-6911.",
        '<h2>Faucet Repair &amp; Installation</h2>'
        '<p>A dripping faucet wastes over 3,000 gallons per year. We repair and replace kitchen, bathroom, and utility faucets throughout Chicagoland. Most faucet jobs take an hour or less.</p>'
        '<h2>Common Faucet Problems</h2>'
        '<ul>'
        '<li><strong>Dripping faucet:</strong> Worn cartridge, O-ring, or valve seat. Quick repair.</li>'
        '<li><strong>Low water pressure:</strong> Clogged aerator, corroded supply lines, or failing cartridge.</li>'
        '<li><strong>Handle won\'t turn:</strong> Mineral buildup or seized cartridge — common with Chicago\'s hard water.</li>'
        '<li><strong>Leaking under the sink:</strong> Failed supply connections or corroded shutoff valves.</li>'
        '<li><strong>Sprayer not working:</strong> Diverter valve issue or clogged sprayer head.</li>'
        '</ul>'
        '<h2>Typical Faucet Service Costs</h2>'
        '<ul>'
        '<li><strong>Faucet repair (cartridge, O-ring):</strong> $100–$250 including parts</li>'
        '<li><strong>Faucet replacement (labor only):</strong> $150–$300</li>'
        '<li><strong>Faucet replacement (with standard faucet):</strong> $250–$500</li>'
        '<li><strong>Shutoff valve replacement:</strong> $75–$200 per valve</li>'
        '</ul>'
        '<p>If your faucet is more than 10 years old and needs repair, a new faucet may make more sense. Modern faucets are more water-efficient and easier to maintain.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Is it worth repairing my old faucet or should I replace it?</h3>'
        '<p>If parts are available and the body is in good shape, repair is cheaper. If the faucet is corroded, the finish is worn, or it\'s builder-grade, replacement gives better long-term value.</p>'
        '<h3>Can I use any faucet with my sink?</h3>'
        '<p>Match the faucet to the number of holes in your sink or countertop. A single-hole faucet won\'t cover a three-hole sink without a deck plate. We can advise before you buy.</p>'
        '<h3>Why is my new faucet\'s water pressure low?</h3>'
        '<p>Check the aerator — they sometimes have a flow restrictor or installation debris. Also make sure supply valves are fully open. If pressure is still low, the issue may be in your supply lines.</p>'
        '<h3>Do you install touchless faucets?</h3>'
        '<p>Yes. Touchless faucets need a power source — usually batteries or an AC adapter. We handle all plumbing connections and make sure the sensor works properly.</p>'
        '<h3>How long does faucet installation take?</h3>'
        '<p>A straightforward swap takes 30–60 minutes. Replacing shutoff valves or supply lines adds another 30 minutes. Removing a stubborn old faucet with corroded connections can add time.</p>'
    )

    svc("garbage-disposal-installation",
        "Garbage Disposal Installation & Repair in Chicago, IL",
        "Garbage disposal installation and repair in Chicago. Jammed, leaking, or new install — licensed plumbers. Call 833-758-6911.",
        '<h2>Garbage Disposal Installation &amp; Repair</h2>'
        '<p>A working garbage disposal makes kitchen cleanup easier. A broken one turns your sink into a swamp. We install new disposals and repair existing ones throughout Chicagoland — from basic 1/3 HP units to heavy-duty 1 HP models for family kitchens.</p>'
        '<h2>Common Disposal Problems</h2>'
        '<ul>'
        '<li><strong>Jammed:</strong> Utensil, bone, or hard object stuck in the grinding chamber.</li>'
        '<li><strong>Won\'t turn on:</strong> Tripped reset button, blown fuse, or burned-out motor.</li>'
        '<li><strong>Leaking:</strong> From sink flange (top), discharge pipe (side), or bottom (internal seal failure).</li>'
        '<li><strong>Slow draining:</strong> Partial clog in the disposal or drain line downstream.</li>'
        '<li><strong>Loud grinding:</strong> Loose impellers, worn bearings, or debris in the chamber.</li>'
        '</ul>'
        '<h2>Typical Garbage Disposal Costs</h2>'
        '<ul>'
        '<li><strong>Repair (jam, reset, drain clearing):</strong> $100–$200</li>'
        '<li><strong>Replacement (standard 1/2 HP):</strong> $200–$400 including unit and labor</li>'
        '<li><strong>Replacement (premium 3/4–1 HP):</strong> $350–$600 including unit and labor</li>'
        '<li><strong>New installation (no existing disposal):</strong> $250–$500 including unit, wiring, and drain</li>'
        '</ul>'
        '<p>If your disposal is humming but not spinning, or leaking from the bottom, replacement is usually more cost-effective than repair.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>What size garbage disposal do I need?</h3>'
        '<p>1–2 people: 1/3 to 1/2 HP. Families of 3–4: 1/2 to 3/4 HP. Heavy cooks or large families: 3/4 to 1 HP. Bigger motors grind faster and jam less.</p>'
        '<h3>Can I put a disposal in my condo?</h3>'
        '<p>Check your building\'s rules — some older Chicago condos prohibit disposals due to aging drain lines. If allowed, we can install one.</p>'
        '<h3>Why does my disposal smell bad?</h3>'
        '<p>Food residue on the splash guard and grinding chamber. Run cold water and ice cubes through to clean. Citrus peels help with odor. Persistent smells may indicate a drain line clog below.</p>'
        '<h3>How long do garbage disposals last?</h3>'
        '<p>8–12 years with normal use. If yours is approaching that age and starting to jam, leak, or grind slowly, replacement beats repair.</p>'
        '<h3>Can you connect my disposal to my dishwasher drain?</h3>'
        '<p>Yes. Most dishwashers drain through the disposal. We remove the knockout plug and connect the dishwasher drain hose securely.</p>'
    )

    svc("sewer-cleaning",
        "Sewer Cleaning Services in Chicago, IL",
        "Professional sewer cleaning in Chicago — hydro jetting, cable machines, root and grease removal. Licensed plumbers. Call 833-758-6911.",
        '<h2>Sewer Cleaning</h2>'
        '<p>When your main sewer line backs up, everything stops — toilets, showers, sinks. Raw sewage comes back up through the lowest drain. We clear sewer blockages with professional-grade cable machines and hydro jetters, and camera-inspect the line afterward to confirm it\'s clear and intact.</p>'
        '<h2>What Causes Sewer Blockages?</h2>'
        '<ul>'
        '<li><strong>Tree roots:</strong> The #1 cause in Chicago. Roots infiltrate clay and cast iron joints and grow until they block the line.</li>'
        '<li><strong>Grease buildup:</strong> Kitchen grease coats the pipe over years, gradually narrowing it.</li>'
        '<li><strong>Paper products and wipes:</strong> "Flushable" wipes don\'t break down — they snag on roots and grease.</li>'
        '<li><strong>Pipe deterioration:</strong> Older clay and cast iron lines develop bellies, cracks, and offsets that trap debris.</li>'
        '<li><strong>Heavy rain:</strong> Chicago\'s combined sewer system means storm surges overwhelm old sewer lines.</li>'
        '</ul>'
        '<h2>Our Cleaning Methods</h2>'
        '<ul>'
        '<li><strong>Cable machine (snake):</strong> Motorized steel cable with cutting head that breaks through roots and debris.</li>'
        '<li><strong>Hydro jetting:</strong> High-pressure water (3,000–4,000 PSI) that scours pipe walls clean. Best for grease and thorough cleaning.</li>'
        '<li><strong>Camera inspection:</strong> Post-cleaning camera run to confirm the line is clear and check pipe condition.</li>'
        '</ul>'
        '<h2>Typical Sewer Cleaning Costs</h2>'
        '<ul>'
        '<li><strong>Cable/snake (standard blockage):</strong> $200–$500</li>'
        '<li><strong>Hydro jetting:</strong> $400–$900</li>'
        '<li><strong>Camera inspection (standalone):</strong> $150–$400</li>'
        '<li><strong>Emergency sewer backup (after-hours):</strong> $350–$800</li>'
        '</ul>'
        '<p>If root intrusion is the cause, you may need periodic cleaning until the line is replaced. We\'ll tell you what we find and what your options are.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How do I know if it\'s my sewer line or just a drain clog?</h3>'
        '<p>One slow fixture = localized drain clog. Multiple slow fixtures, especially on the lowest level = main sewer line. Sewage through a basement floor drain is the clearest sign.</p>'
        '<h3>How often should I have my sewer line cleaned?</h3>'
        '<p>If you\'ve had backups: every 1–2 years. Large trees near the line: annual cleaning. Newer PVC lines with no tree issues may never need it.</p>'
        '<h3>Will sewer cleaning damage my pipes?</h3>'
        '<p>Professional equipment is designed to clean without damage. If pipes are severely deteriorated, cleaning may reveal underlying problems — better to find them during maintenance than during a backup.</p>'
        '<h3>What\'s the difference between cable and hydro jetting?</h3>'
        '<p>Cable punches through the blockage. Hydro jetting cleans the entire pipe wall and removes grease and scale. Jetting is more thorough and lasts longer — like pressure-washing the inside of the pipe.</p>'
        '<h3>Do you clean sewer lines in winter?</h3>'
        '<p>Yes, year-round. Sewer backups don\'t take the winter off, and neither do we. Our crews are equipped for Chicago winters.</p>'
    )

    svc("sewer-replacement",
        "Sewer Line Replacement in Chicago, IL",
        "Sewer line replacement in Chicago — trenchless and traditional methods for cracked, collapsed, or root-damaged lines. Call 833-758-6911.",
        '<h2>Sewer Line Replacement</h2>'
        '<p>When cleaning can\'t fix it — because the pipe is cracked, collapsed, bellied, or disintegrating — replacement is the answer. We replace sewer lines using both traditional excavation and trenchless methods, depending on what makes sense for your property.</p>'
        '<h2>Signs You Need Replacement</h2>'
        '<ul>'
        '<li><strong>Recurring backups</strong> even after professional cleaning</li>'
        '<li><strong>Camera inspection</strong> showing cracks, offsets, bellies, or pervasive root infiltration</li>'
        '<li><strong>Sewage odor</strong> in your yard or basement</li>'
        '<li><strong>Sinkholes or wet spots</strong> along the sewer line path</li>'
        '<li><strong>Old pipe material:</strong> Orangeburg, clay, or severely corroded cast iron</li>'
        '</ul>'
        '<h2>Replacement Methods</h2>'
        '<ul>'
        '<li><strong>Traditional excavation:</strong> Trench along the line, remove old pipe, lay new PVC. Best for collapsed lines.</li>'
        '<li><strong>Pipe bursting (trenchless):</strong> New HDPE pipe pulled through old one. Minimal digging — usually just two access pits.</li>'
        '<li><strong>Pipe lining (CIPP):</strong> Resin-coated liner cured inside existing pipe. Good for cracks and joint issues without major collapse.</li>'
        '</ul>'
        '<h2>Typical Sewer Replacement Costs</h2>'
        '<ul>'
        '<li><strong>Traditional excavation:</strong> $5,000–$15,000</li>'
        '<li><strong>Trenchless pipe bursting:</strong> $6,000–$18,000</li>'
        '<li><strong>CIPP lining:</strong> $4,000–$12,000</li>'
        '<li><strong>Landscape/concrete restoration:</strong> $500–$3,000+ (may be included)</li>'
        '</ul>'
        '<p>Permits and inspections are typically required. We handle the paperwork. Costs vary by pipe length, depth, access, and obstacles.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long does sewer replacement take?</h3>'
        '<p>Traditional excavation: 1–3 days. Trenchless methods: often completed in a single day. CIPP lining: 1–2 days including cure time.</p>'
        '<h3>Is trenchless always better?</h3>'
        '<p>Not always. Trenchless works when the existing pipe is relatively straight and hasn\'t fully collapsed. Severe bellies, offsets, or total collapse may require traditional excavation. A camera inspection tells us which method works.</p>'
        '<h3>How long will the new sewer line last?</h3>'
        '<p>PVC and HDPE sewer pipes have a 50–100+ year lifespan. They don\'t corrode, resist roots better than clay or cast iron, and handle Chicago\'s freeze-thaw cycles well.</p>'
        '<h3>Do I need to replace the whole line or just part?</h3>'
        '<p>Depends on the camera findings. Isolated damage = spot repair. Entire line deteriorated = full replacement prevents future problems and repeated repairs.</p>'
        '<h3>Will sewer replacement tear up my yard?</h3>'
        '<p>Traditional excavation requires trenching. We restore the trench and replace sod. Trenchless methods minimize this — typically just two small pits at each end.</p>'
    )

    svc("sewer-camera-inspection",
        "Sewer Camera Inspection in Chicago, IL",
        "Sewer camera inspection in Chicago — see inside your sewer line before you dig. Root intrusion, cracks, blockages identified. Call 833-758-6911.",
        '<h2>Sewer Camera Inspection</h2>'
        '<p>A sewer camera inspection lets us see exactly what\'s happening inside your sewer line without digging. We push a waterproof camera through the pipe on a flexible cable and watch the live feed. It shows roots, cracks, offsets, grease buildup, bellies, and blockages — and tells us exactly where the problem is.</p>'
        '<h2>When to Get a Camera Inspection</h2>'
        '<ul>'
        '<li><strong>Recurring drain or sewer backups</strong> — to find the root cause</li>'
        '<li><strong>Buying a home</strong> — especially in Chicago where sewer lines are often 50+ years old</li>'
        '<li><strong>After sewer cleaning</strong> — to confirm the line is clear and check condition</li>'
        '<li><strong>Before a remodel</strong> — to assess the line before adding fixtures</li>'
        '<li><strong>Sewage odor</strong> that can\'t be explained by a simple clog</li>'
        '</ul>'
        '<h2>What the Camera Reveals</h2>'
        '<ul>'
        '<li><strong>Root intrusion:</strong> Roots growing through pipe joints — very common in clay lines</li>'
        '<li><strong>Cracks and fractures:</strong> From settling, frost heave, or age</li>'
        '<li><strong>Bellies (sags):</strong> Low spots where water and debris collect</li>'
        '<li><strong>Offsets:</strong> Pipe sections shifted apart at joints</li>'
        '<li><strong>Pipe material and condition:</strong> Clay, cast iron, Orangeburg, PVC — we identify what you have</li>'
        '</ul>'
        '<h2>Typical Camera Inspection Costs</h2>'
        '<ul>'
        '<li><strong>Standard inspection:</strong> $150–$400</li>'
        '<li><strong>With sewer cleaning (bundled):</strong> $350–$700 combined</li>'
        '<li><strong>Locator service (marking pipe path):</strong> $100–$200 add-on</li>'
        '</ul>'
        '<p>A camera inspection is one of the best investments before buying a home or deciding on repair vs. replacement.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How does a sewer camera inspection work?</h3>'
        '<p>We access your sewer line through a cleanout. The camera head is pushed through the line on a flexible cable. Video shows the pipe interior in real time, and a location transmitter marks problems from above ground.</p>'
        '<h3>Should I get one before buying a house?</h3>'
        '<p>In Chicago, absolutely. Standard home inspections don\'t include the sewer line. A $200–$400 camera inspection can save you from a $10,000+ surprise replacement after closing.</p>'
        '<h3>How long does an inspection take?</h3>'
        '<p>30–60 minutes. We show you the footage in real time and explain what we\'re seeing. You get a summary and our recommendation for next steps.</p>'
        '<h3>Can the camera reach the city main?</h3>'
        '<p>In most cases, yes. Our cameras travel 100+ feet. If a blockage prevents passage, we note the location and nature of the obstruction.</p>'
        '<h3>Do you provide a recording?</h3>'
        '<p>Yes. We provide video or photos for your records — especially useful for real estate transactions or insurance claims.</p>'
    )

    svc("sewer-cleanout-installation",
        "Sewer Cleanout Installation in Chicago, IL",
        "Sewer cleanout installation in Chicago — easy access for future sewer maintenance and inspections. Licensed plumbers. Call 833-758-6911.",
        '<h2>Sewer Cleanout Installation</h2>'
        '<p>A sewer cleanout is a capped access point that lets a plumber quickly access the line for cleaning and camera inspections. Many older Chicago homes don\'t have one, which means every sewer backup requires pulling a toilet or digging. Installing a cleanout saves time and money on every future service call.</p>'
        '<h2>Why You Need a Cleanout</h2>'
        '<ul>'
        '<li><strong>Faster service:</strong> Plumbers access the line in minutes instead of removing fixtures</li>'
        '<li><strong>Lower costs:</strong> No extra labor to pull and reset a toilet each time</li>'
        '<li><strong>Camera inspections:</strong> Ideal entry point for sewer cameras</li>'
        '<li><strong>Code compliance:</strong> Required for new construction and major sewer work</li>'
        '<li><strong>Real estate value:</strong> Buyers and inspectors look for accessible cleanouts</li>'
        '</ul>'
        '<h2>Types of Cleanouts</h2>'
        '<ul>'
        '<li><strong>Interior:</strong> In the basement where the sewer exits the foundation. Year-round access.</li>'
        '<li><strong>Exterior:</strong> In the yard near the property line. Access to main run.</li>'
        '<li><strong>Two-way:</strong> Access in both directions — toward house and toward street.</li>'
        '</ul>'
        '<h2>Typical Cleanout Installation Costs</h2>'
        '<ul>'
        '<li><strong>Interior (basement):</strong> $400–$1,000</li>'
        '<li><strong>Exterior (yard):</strong> $800–$2,000</li>'
        '<li><strong>Two-way cleanout:</strong> $1,000–$2,500</li>'
        '</ul>'
        '<p>The cost pays for itself quickly with regular sewer maintenance. Without a cleanout, each cleaning call costs extra for toilet removal.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How do I know if my house has a cleanout?</h3>'
        '<p>Look for a capped pipe (usually 4 inches) in your yard near the foundation, or in your basement near the main drain exit. If you can\'t find one, you probably don\'t have one — common in older Chicago homes.</p>'
        '<h3>Does installation require digging?</h3>'
        '<p>Exterior cleanouts require excavation. Interior cleanouts involve cutting into the drain pipe — no digging, but concrete may need to be cut if under the slab.</p>'
        '<h3>Is a cleanout required by code?</h3>'
        '<p>For new construction and significant sewer work, yes. Existing homes without one aren\'t retroactively required to add one, but it\'s one of the smartest plumbing upgrades you can make.</p>'
        '<h3>Can you add a cleanout during other sewer work?</h3>'
        '<p>Absolutely — and that\'s the most cost-effective time. If we\'re already accessing or replacing your sewer line, adding a cleanout is significantly cheaper as an add-on.</p>'
        '<h3>How long does installation take?</h3>'
        '<p>Interior: 2–4 hours. Exterior: half to full day depending on depth and soil. We restore excavated areas to grade when done.</p>'
    )

    svc("drain-cleaning",
        "Drain Cleaning Services in Chicago, IL",
        "Professional drain cleaning in Chicago — kitchen, bathroom, floor drains, main lines. Licensed plumbers with proper equipment. Call 833-758-6911.",
        '<h2>Drain Cleaning</h2>'
        '<p>A slow drain is a clogged drain that hasn\'t finished clogging yet. Whether it\'s the kitchen sink, bathroom shower, or basement floor drain, we clear it with the right tool — not a bottle of chemical drain cleaner that eats your pipes from the inside out.</p>'
        '<h2>Common Drain Problems</h2>'
        '<ul>'
        '<li><strong>Kitchen drains:</strong> Grease, food particles, and soap buildup that narrows the pipe over time.</li>'
        '<li><strong>Bathroom drains:</strong> Hair, soap scum, and toothpaste. Shower and tub drains are the worst offenders.</li>'
        '<li><strong>Floor drains:</strong> Sediment, debris, and dried-out traps. Can also back up from the sewer.</li>'
        '<li><strong>Laundry drains:</strong> Lint and detergent residue clog more than people expect.</li>'
        '<li><strong>Multiple slow drains:</strong> Problem is downstream — possibly your main sewer line.</li>'
        '</ul>'
        '<h2>How We Clean Drains</h2>'
        '<ul>'
        '<li><strong>Hand snake:</strong> Flexible cable for sink and tub clogs within 25 feet of the fixture.</li>'
        '<li><strong>Motorized drain machine:</strong> Powered cable for tougher blockages in larger lines.</li>'
        '<li><strong>Hydro jetting:</strong> High-pressure water that scours the pipe clean. Best for grease and recurring problems.</li>'
        '</ul>'
        '<h2>Typical Drain Cleaning Costs</h2>'
        '<ul>'
        '<li><strong>Single drain (sink, tub, shower):</strong> $100–$250</li>'
        '<li><strong>Main drain line:</strong> $200–$400</li>'
        '<li><strong>Hydro jetting:</strong> $400–$900</li>'
        '<li><strong>Floor drain cleaning:</strong> $150–$300</li>'
        '</ul>'
        '<p>Chemical drain cleaners corrode pipes — especially the older cast iron and galvanized lines common in Chicago homes. Professional cleaning is safer and more effective.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Are chemical drain cleaners safe?</h3>'
        '<p>We don\'t recommend them. Caustic chemicals corrode pipes, especially older metal pipes. They also don\'t work on complete blockages and can make a plumber\'s job harder if sitting in the drain when we arrive.</p>'
        '<h3>Why does my drain keep clogging?</h3>'
        '<p>Recurring clogs usually mean buildup that a quick snake isn\'t fully removing, or a structural pipe issue — belly, offset, or root intrusion. A camera inspection shows what\'s going on.</p>'
        '<h3>How often should drains be professionally cleaned?</h3>'
        '<p>Most drains don\'t need regular cleaning with proper use. Kitchen drains benefit from professional cleaning every 1–2 years if you cook frequently. Sewer lines with root issues may need annual maintenance.</p>'
        '<h3>Can I prevent drain clogs?</h3>'
        '<p>Use drain strainers. Don\'t pour grease down the drain — wipe greasy pans with a paper towel first. Run hot water after dishes. Never flush anything besides toilet paper.</p>'
        '<h3>What if my floor drain smells bad?</h3>'
        '<p>The P-trap holds water to block sewer gas. If the drain isn\'t used regularly, water evaporates. Pour a bucket of water in to refill the trap. If the smell persists, there may be a blockage or broken trap.</p>'
    )
