"""Service rewrites batch 1: emergency-plumber through dishwasher-install."""

def register(svc):

    svc("emergency-plumber",
        "24/7 Emergency Plumber in Chicago, IL",
        "Burst pipe? Sewer backup? Gas leak? Licensed emergency plumbers in Chicago respond fast, 24/7. Call 833-758-6911 now.",
        '<h2>Emergency Plumbing — When Minutes Matter</h2>'
        '<p>A burst pipe at 2 a.m. doesn\'t wait for business hours. Neither do we. Plumbers 911 connects you with licensed emergency plumbers across Chicagoland who respond fast — day or night, weekends and holidays included.</p>'
        '<p>Whether it\'s a flooded basement, a sewer backup pushing waste into your home, or a gas line you can smell, we dispatch experienced plumbers who show up with the tools and parts to handle it on the spot.</p>'
        '<h2>What Counts as a Plumbing Emergency?</h2>'
        '<ul>'
        '<li><strong>Burst or broken pipes</strong> — especially in winter when Chicago temps drop below zero</li>'
        '<li><strong>Sewer backups</strong> — sewage coming up through floor drains or toilets</li>'
        '<li><strong>Gas leaks</strong> — if you smell gas, leave the house and call immediately</li>'
        '<li><strong>No water</strong> — complete loss of water pressure or supply</li>'
        '<li><strong>Flooding</strong> — from a failed sump pump, broken supply line, or water heater rupture</li>'
        '<li><strong>Frozen pipes</strong> — before they burst, a plumber can thaw them safely</li>'
        '</ul>'
        '<h2>What We Do on an Emergency Call</h2>'
        '<p>When you call, we connect you with the nearest available plumber. They\'ll walk you through immediate steps — like shutting off your main water valve — while en route. On arrival, the plumber assesses the situation, stops the damage, and makes the repair. If a full repair requires follow-up work, they\'ll stabilize the issue that night and schedule the rest.</p>'
        '<h2>Typical Emergency Plumbing Costs</h2>'
        '<p>Emergency service rates are higher than scheduled work due to after-hours response and urgency. Here\'s what to expect in the Chicago area:</p>'
        '<ul>'
        '<li><strong>Emergency service call:</strong> $150–$350 (includes dispatch and first hour of labor)</li>'
        '<li><strong>Burst pipe repair:</strong> $200–$600 depending on location and pipe material</li>'
        '<li><strong>Sewer backup clearing:</strong> $300–$700 depending on blockage severity</li>'
        '<li><strong>Water heater emergency shutoff and repair:</strong> $200–$500</li>'
        '<li><strong>Gas line emergency repair:</strong> $300–$800+</li>'
        '</ul>'
        '<p>Costs vary by time of day, complexity, and materials needed. Your plumber will explain the scope and cost before starting non-emergency follow-up work.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How fast can an emergency plumber get to my Chicago home?</h3>'
        '<p>Most emergency calls are responded to within 30–60 minutes, depending on your location and current demand. We cover all of Chicago and the surrounding suburbs.</p>'
        '<h3>Do emergency plumbers charge more on weekends and holidays?</h3>'
        '<p>After-hours, weekend, and holiday rates are typically higher than standard business-hour rates. Expect a premium of $50–$150 over normal service call fees. Your plumber will discuss pricing before beginning work.</p>'
        '<h3>What should I do while waiting for the plumber?</h3>'
        '<p>Shut off the water at the main valve if there\'s active flooding. If you smell gas, leave the house immediately and call from outside. Move valuables away from standing water. Don\'t attempt electrical work near water.</p>'
        '<h3>Can an emergency plumber fix a frozen pipe before it bursts?</h3>'
        '<p>Yes. Plumbers use controlled heat methods to safely thaw frozen pipes. If you notice reduced water pressure in winter or frost on exposed pipes, call before it becomes a burst — the repair is much cheaper.</p>'
        '<h3>Are your emergency plumbers licensed and insured?</h3>'
        '<p>Every plumber in our network is licensed by the State of Illinois and carries full liability insurance. We verify credentials before adding anyone to our referral network.</p>'
    )

    svc("residential-plumbing",
        "Residential Plumbing Services in Chicago, IL",
        "Complete residential plumbing for Chicago homes — repairs, installations, remodels, and maintenance. Licensed plumbers, 24/7. Call 833-758-6911.",
        '<h2>Residential Plumbing for Chicago Homes</h2>'
        '<p>From a dripping faucet in a Lincoln Park condo to a full repipe of a 1920s bungalow in Berwyn, we handle every residential plumbing job in Chicagoland. Our licensed plumbers know the housing stock — Greystones, two-flats, ranch homes, new construction — and the unique plumbing challenges each one brings.</p>'
        '<h2>What We Cover</h2>'
        '<ul>'
        '<li><strong>Repairs:</strong> Leaky faucets, running toilets, dripping pipes, slow drains, water pressure problems</li>'
        '<li><strong>Installations:</strong> Fixtures, water heaters, garbage disposals, dishwashers, water filtration systems</li>'
        '<li><strong>Drain &amp; sewer:</strong> Cleaning, camera inspections, line replacement</li>'
        '<li><strong>Remodeling:</strong> Kitchen and bathroom rough-in, fixture placement, supply and drain relocations</li>'
        '<li><strong>Maintenance:</strong> Seasonal checkups, water heater flushes, sump pump testing, backflow prevention</li>'
        '</ul>'
        '<h2>Common Residential Plumbing Issues in Chicago</h2>'
        '<p>Chicago\'s older housing stock means we see a lot of the same problems: galvanized steel pipes corroding from the inside out, cast iron sewer lines cracked by tree roots, and lead service lines that need replacement. Newer homes aren\'t immune either — builder-grade fixtures fail, and settling foundations can stress drain lines.</p>'
        '<p>We also see seasonal patterns. Winter brings frozen pipes and water heater failures. Spring means sump pump overloads. Summer is remodeling season. We\'re busy year-round because Chicago homes keep us busy year-round.</p>'
        '<h2>Typical Residential Plumbing Costs</h2>'
        '<ul>'
        '<li><strong>Service call + minor repair:</strong> $150–$300 (faucet fix, toilet repair, small leak)</li>'
        '<li><strong>Fixture installation:</strong> $200–$500 per fixture (faucet, toilet, garbage disposal)</li>'
        '<li><strong>Water heater replacement:</strong> $800–$2,000 (tank) or $2,500–$5,000 (tankless)</li>'
        '<li><strong>Drain cleaning:</strong> $150–$400 depending on method and access</li>'
        '<li><strong>Whole-house repipe:</strong> $4,000–$15,000+ depending on home size and pipe material</li>'
        '</ul>'
        '<p>Every job is different. Your plumber will assess the situation and discuss costs before starting work.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Do you work on older Chicago homes with galvanized or lead pipes?</h3>'
        '<p>Absolutely. That\'s a big part of what we do. We regularly repipe homes built before 1960 that still have galvanized supply lines or lead service connections. We\'ll recommend the best replacement material — typically copper or PEX — based on your home\'s layout and your budget.</p>'
        '<h3>Can you handle both the plumbing and permit for a bathroom remodel?</h3>'
        '<p>Yes. Our plumbers pull permits when required by the City of Chicago or suburban municipalities. We know the local codes and inspection requirements, so you don\'t have to worry about compliance.</p>'
        '<h3>How long does a typical residential plumbing repair take?</h3>'
        '<p>Most repairs — leaky faucet, running toilet, small leak — take 1–2 hours. Larger jobs like water heater replacements take half a day. Repiping or sewer line work may take 1–3 days depending on scope.</p>'
        '<h3>Do you offer plumbing inspections for home buyers?</h3>'
        '<p>Yes. We do pre-purchase plumbing inspections that go deeper than a standard home inspection. We check supply lines, drain condition, water heater age, sewer line status via camera inspection, and water pressure.</p>'
        '<h3>What areas do you serve beyond Chicago city limits?</h3>'
        '<p>We cover all of Cook County and the surrounding collar counties — DuPage, Will, Lake, Kane, McHenry, Kendall, DeKalb, and Grundy. If you\'re in the Chicagoland area, we\'ve got you covered.</p>'
    )

    svc("commercial-plumbing",
        "Commercial Plumbing Services in Chicago, IL",
        "Commercial plumbing for Chicago businesses — restaurants, offices, retail, multi-unit buildings. Licensed, code-compliant. Call 833-758-6911.",
        '<h2>Commercial Plumbing for Chicago Businesses</h2>'
        '<p>Commercial plumbing is a different animal than residential. Higher volumes, stricter codes, grease traps, backflow preventers, and systems that can\'t go down without costing you money every hour. We work with restaurants, office buildings, retail spaces, multi-unit residential properties, and industrial facilities across Chicagoland.</p>'
        '<h2>Commercial Services We Provide</h2>'
        '<ul>'
        '<li><strong>Drain and sewer maintenance:</strong> Scheduled cleaning, grease trap service, camera inspections</li>'
        '<li><strong>Backflow prevention:</strong> Testing, installation, and certification per Illinois code</li>'
        '<li><strong>Water heater systems:</strong> Commercial tank and tankless units, boiler connections</li>'
        '<li><strong>Fixture installation:</strong> ADA-compliant restrooms, commercial kitchen plumbing, bar sinks</li>'
        '<li><strong>Gas line work:</strong> Restaurant equipment hookups, gas line repairs and extensions</li>'
        '<li><strong>Emergency service:</strong> 24/7 response for flooding, sewer backups, and pipe failures</li>'
        '<li><strong>Tenant buildouts:</strong> Plumbing rough-in for new commercial spaces</li>'
        '</ul>'
        '<h2>Typical Commercial Plumbing Costs</h2>'
        '<ul>'
        '<li><strong>Commercial service call:</strong> $200–$400 (includes diagnostic and first hour)</li>'
        '<li><strong>Grease trap cleaning:</strong> $200–$500 depending on trap size</li>'
        '<li><strong>Backflow preventer testing:</strong> $75–$200 per device</li>'
        '<li><strong>Commercial water heater replacement:</strong> $2,000–$8,000+ depending on capacity</li>'
        '<li><strong>Tenant buildout plumbing:</strong> $3,000–$15,000+ depending on scope</li>'
        '</ul>'
        '<p>Commercial jobs are quoted individually based on scope, access, and code requirements. We provide detailed written quotes for larger projects.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Do you handle Chicago commercial plumbing permits?</h3>'
        '<p>Yes. We pull all required permits and schedule inspections with the City of Chicago or the relevant municipality. Our plumbers know commercial codes and make sure the work passes inspection the first time.</p>'
        '<h3>Can you work around our business hours to minimize disruption?</h3>'
        '<p>Absolutely. We schedule commercial work for evenings, weekends, or off-peak hours when that makes sense for your operation. For restaurants, we typically work between service hours or overnight.</p>'
        '<h3>Do you provide maintenance contracts for commercial properties?</h3>'
        '<p>Yes. We work with property managers and business owners on scheduled maintenance plans — regular drain cleaning, backflow testing, water heater inspections, and seasonal prep work.</p>'
        '<h3>How quickly can you respond to a commercial plumbing emergency?</h3>'
        '<p>We offer 24/7 emergency response for commercial accounts. Most emergency calls are dispatched within the hour. If you have a sewer backup in a restaurant or flooding in an occupied building, call immediately.</p>'
        '<h3>Are your plumbers licensed for commercial work in Chicago?</h3>'
        '<p>Every plumber in our network holds the appropriate Illinois state license for commercial plumbing work. We also carry full liability and workers\' compensation insurance.</p>'
    )

    svc("bathroom-remodeling",
        "Bathroom Remodeling Plumbing in Chicago, IL",
        "Expert bathroom remodeling plumbing in Chicago — fixture installs, supply lines, drains, shower valves, ADA upgrades. Call 833-758-6911.",
        '<h2>Bathroom Remodeling Plumbing Done Right</h2>'
        '<p>A bathroom remodel isn\'t just tile and vanities — the plumbing behind the walls is what makes it all work. We handle the rough-in, supply lines, drain relocations, fixture installations, and everything in between. Whether you\'re updating a half-bath or gutting a master suite, we make sure the plumbing is solid before the finish work goes in.</p>'
        '<h2>What We Handle</h2>'
        '<ul>'
        '<li><strong>Fixture installation:</strong> Toilets, sinks, faucets, showerheads, tub fillers</li>'
        '<li><strong>Shower and tub plumbing:</strong> Valve replacement, tub-to-shower conversions, custom shower builds</li>'
        '<li><strong>Supply line upgrades:</strong> Replacing old galvanized lines with copper or PEX</li>'
        '<li><strong>Drain relocations:</strong> Moving drains for new layouts</li>'
        '<li><strong>ADA-compliant installations:</strong> Walk-in tubs, barrier-free showers, grab bars</li>'
        '</ul>'
        '<h2>Chicago-Specific Considerations</h2>'
        '<p>Bathroom remodels in Chicago\'s older homes often reveal surprises — galvanized pipes that crumble when you touch them, cast iron drains that have rusted through, or non-standard framing that requires creative plumbing solutions. In multi-unit buildings, you also need to coordinate with neighbors and the building association. We\'ve done hundreds of bathroom remodels in every type of Chicago housing.</p>'
        '<h2>Typical Bathroom Remodeling Plumbing Costs</h2>'
        '<ul>'
        '<li><strong>Basic fixture swap (same locations):</strong> $1,500–$3,000 for toilet, sink, and shower/tub valve</li>'
        '<li><strong>Fixture relocation (moving drains/supply):</strong> $3,000–$6,000+</li>'
        '<li><strong>Full bathroom rough-in (new bathroom):</strong> $5,000–$10,000+ including supply, drain, and vent</li>'
        '<li><strong>Tub-to-shower conversion:</strong> $1,500–$4,000 plumbing portion</li>'
        '<li><strong>Shower valve replacement:</strong> $300–$800 including valve and labor</li>'
        '</ul>'
        '<p>These are plumbing costs only. Tile, cabinetry, and finish work are separate. Costs vary based on access, pipe material, and code requirements.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Do I need a permit for a bathroom remodel in Chicago?</h3>'
        '<p>If you\'re moving plumbing — relocating drains, adding a new bathroom, or changing fixture locations — yes. Simple fixture swaps in the same location typically don\'t require a permit. We pull permits when required.</p>'
        '<h3>Can you move my shower drain to a different location?</h3>'
        '<p>Yes. On a concrete slab, this involves cutting the slab and rerouting the drain. On a wood-framed floor, the process is simpler. Both are very doable.</p>'
        '<h3>How long does the plumbing portion take?</h3>'
        '<p>Rough-in work takes 1–2 days. Fixture installation after tile and finish work takes another half day to a full day. We coordinate with your general contractor on timing.</p>'
        '<h3>Should I replace old pipes while the walls are open?</h3>'
        '<p>If the walls are already open, that\'s the time to do it. Replacing corroded galvanized lines or deteriorated cast iron while you have access saves you from tearing things apart again later.</p>'
        '<h3>Do you work with my contractor, or do I hire you separately?</h3>'
        '<p>Either way works. Many GCs bring us in as their plumbing sub. You can also hire us directly. We\'re flexible and communicate clearly with all parties involved.</p>'
    )

    svc("toilet-install",
        "Toilet Repair & Installation in Chicago, IL",
        "Toilet repair, replacement, and installation in Chicago. Running toilets, clogs, new installs — licensed plumbers. Call 833-758-6911.",
        '<h2>Toilet Repair &amp; Installation</h2>'
        '<p>A toilet that won\'t stop running, won\'t flush properly, or keeps clogging isn\'t just annoying — it\'s wasting water and money. We fix and replace toilets in homes and businesses across Chicagoland. It\'s one of our most common calls, and it\'s usually a quick fix.</p>'
        '<h2>Common Toilet Problems We Fix</h2>'
        '<ul>'
        '<li><strong>Running toilet:</strong> Usually a faulty flapper, fill valve, or overflow tube. Quick repair, big water savings.</li>'
        '<li><strong>Weak or incomplete flush:</strong> Clogged rim jets, low water level, or a partially blocked trap.</li>'
        '<li><strong>Constant clogs:</strong> Could be the toilet itself or a deeper drain issue.</li>'
        '<li><strong>Leaking at the base:</strong> Failed wax ring — needs replacement before subfloor damage.</li>'
        '<li><strong>Cracked tank or bowl:</strong> Can\'t be repaired. Replacement is the only fix.</li>'
        '</ul>'
        '<h2>Typical Toilet Service Costs</h2>'
        '<ul>'
        '<li><strong>Toilet repair (flapper, fill valve, handle):</strong> $100–$250 including parts</li>'
        '<li><strong>Wax ring replacement:</strong> $150–$300 (toilet must be pulled and reset)</li>'
        '<li><strong>Toilet replacement (standard):</strong> $300–$600 labor or $450–$900 with toilet included</li>'
        '<li><strong>Flange repair:</strong> $150–$400 depending on damage</li>'
        '</ul>'
        '<p>If your toilet needs frequent repairs, replacing it with a modern water-efficient model is usually more cost-effective long term.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How do I know if my toilet needs repair or replacement?</h3>'
        '<p>Single issues like a running flapper or loose handle — repair makes sense. Constant clogs, cracks, or multiple failing parts on a 15+ year old toilet — replacement is the better investment.</p>'
        '<h3>What kind of toilet should I buy?</h3>'
        '<p>A standard two-piece with a 1.28 GPF rating works well for most Chicago homes. Elongated bowls are more comfortable; round bowls save space in tight bathrooms. Pressure-assisted models flush more powerfully.</p>'
        '<h3>Can I install a toilet myself?</h3>'
        '<p>A basic swap is possible, but an improperly set wax ring causes hidden leaks, and a broken flange means water damage to the ceiling below. Pro install ensures it\'s sealed, level, and leak-free.</p>'
        '<h3>Why does my toilet keep clogging?</h3>'
        '<p>Could be a narrow trapway (common in older low-flow models), a partially blocked downstream drain, or sewer line buildup. If multiple fixtures are slow, the issue is in your drain or sewer line.</p>'
        '<h3>How long does a toilet installation take?</h3>'
        '<p>About 1–2 hours for a straightforward replacement. Flange repair or floor work adds another hour. New installations requiring drain and supply work take half a day.</p>'
    )

    svc("kitchen-remodeling",
        "Kitchen Remodeling Plumbing in Chicago, IL",
        "Kitchen remodeling plumbing in Chicago — sink installs, dishwasher hookups, gas lines, drain relocations. Call 833-758-6911.",
        '<h2>Kitchen Remodeling Plumbing</h2>'
        '<p>The kitchen is the most plumbing-intensive room in your house. Sink, dishwasher, garbage disposal, ice maker line, gas line for the stove, pot filler — every one needs supply lines, drain connections, or gas hookups done right. We handle the plumbing side so your contractor can focus on cabinets and countertops.</p>'
        '<h2>Kitchen Plumbing Services</h2>'
        '<ul>'
        '<li><strong>Sink installation:</strong> Undermount, farmhouse, double-bowl — supply and drain for any style</li>'
        '<li><strong>Faucet installation:</strong> Standard, pull-down, touchless, pot fillers</li>'
        '<li><strong>Dishwasher hookup:</strong> Supply line, drain connection, and air gap</li>'
        '<li><strong>Garbage disposal:</strong> New installation or replacement</li>'
        '<li><strong>Gas line work:</strong> Hookups for gas ranges, new gas lines for relocated stoves</li>'
        '<li><strong>Drain relocations:</strong> Moving the sink drain for a new layout</li>'
        '<li><strong>Ice maker lines:</strong> Refrigerator water supply for ice and filtered water</li>'
        '</ul>'
        '<h2>Typical Kitchen Plumbing Costs</h2>'
        '<ul>'
        '<li><strong>Sink + faucet installation (same location):</strong> $300–$600 labor</li>'
        '<li><strong>Sink relocation (new drain/supply run):</strong> $1,500–$4,000+</li>'
        '<li><strong>Dishwasher hookup:</strong> $150–$350</li>'
        '<li><strong>Garbage disposal installation:</strong> $200–$450 including unit</li>'
        '<li><strong>Gas line for range:</strong> $300–$800 new run; $150–$300 hookup to existing</li>'
        '<li><strong>Full kitchen rough-in (new layout):</strong> $3,000–$8,000+</li>'
        '</ul>'
        '<p>Costs depend on whether you\'re keeping the same layout or moving things. Same-location fixture swaps are quick. Relocating a sink to an island adds significant drain and vent work.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Can you move my kitchen sink to an island?</h3>'
        '<p>Yes, but it\'s one of the more involved tasks. An island sink requires running supply and drain lines under the floor, plus proper venting. It\'s very doable — it just needs to be planned and budgeted for.</p>'
        '<h3>Do I need a gas line run for my new range?</h3>'
        '<p>If switching from electric to gas or relocating your range, you\'ll need a new gas line. This requires a licensed plumber, pressure test, and permit. We handle all of it.</p>'
        '<h3>Should I replace supply lines and shutoff valves during a remodel?</h3>'
        '<p>If the walls are open, yes. Old gate valves corrode and fail. We replace them with quarter-turn ball valves and braided stainless supply lines — reliable and code-compliant.</p>'
        '<h3>Can you install a pot filler above my stove?</h3>'
        '<p>Yes. A pot filler requires a cold water supply run to the wall behind the range. Easiest during a remodel, but doable as a retrofit with minimal wall repair.</p>'
        '<h3>How do you coordinate with my general contractor?</h3>'
        '<p>We schedule rough-in after demo and framing, before drywall. Then we return for fixture installation after countertops are set. We communicate directly with your GC on timing.</p>'
    )

    svc("dishwasher-install",
        "Dishwasher Installation in Chicago, IL",
        "Professional dishwasher installation in Chicago — supply line, drain hookup, proper connection. Licensed plumbers. Call 833-758-6911.",
        '<h2>Dishwasher Installation</h2>'
        '<p>Installing a dishwasher is more than sliding it under the counter. It needs a hot water supply line, a drain connection with air gap to prevent backflow, and an electrical hookup. We install new dishwashers and replace old ones in homes across Chicagoland.</p>'
        '<h2>What the Installation Includes</h2>'
        '<ul>'
        '<li><strong>Hot water supply connection:</strong> Tap into your hot water line with a proper shutoff valve</li>'
        '<li><strong>Drain hookup:</strong> Connected to sink drain or disposal with required high loop or air gap</li>'
        '<li><strong>Leveling and securing:</strong> Anchored to countertop and tested for leaks</li>'
        '<li><strong>Old unit removal:</strong> Disconnect and pull out the old dishwasher</li>'
        '<li><strong>Supply line upgrade:</strong> Replace corroded valves that don\'t shut off properly</li>'
        '</ul>'
        '<h2>Typical Installation Costs</h2>'
        '<ul>'
        '<li><strong>Standard replacement (existing hookups):</strong> $150–$300 labor</li>'
        '<li><strong>New installation (no existing hookups):</strong> $300–$600 including supply, drain, and valve</li>'
        '<li><strong>Supply valve replacement (add-on):</strong> $75–$150</li>'
        '</ul>'
        '<p>These are labor and connection costs — the dishwasher itself is separate.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Can you install a dishwasher where there wasn\'t one before?</h3>'
        '<p>Yes. We\'ll run a hot water supply and drain connection from your kitchen sink area. Straightforward as long as there\'s cabinet space within reasonable distance of the sink.</p>'
        '<h3>Do I need an air gap for my dishwasher?</h3>'
        '<p>Illinois code requires either an air gap or a high drain loop to prevent backflow. We install whichever is appropriate for your setup.</p>'
        '<h3>Should I repair or replace a leaking dishwasher?</h3>'
        '<p>If it\'s over 8–10 years old and the leak is from the tub, pump, or door seal, replacement usually makes more sense. A loose connection at supply or drain is a quick fix.</p>'
        '<h3>How long does installation take?</h3>'
        '<p>Standard replacement: 1–1.5 hours. New installation with supply and drain runs: 2–3 hours. We test for leaks and run a short cycle before leaving.</p>'
        '<h3>Can you install any brand of dishwasher?</h3>'
        '<p>Yes. Standard dishwashers are 24 inches wide with the same connection types. We install Bosch, Samsung, LG, KitchenAid, Whirlpool, GE, and every other major brand.</p>'
    )
