"""Service rewrites batch 4: water-softener through water-leak-detection-repair."""

def register(svc):

    svc("water-softener-installation",
        "Water Softener Installation in Chicago, IL",
        "Water softener installation in Chicago — hard water solutions for homes and businesses. Licensed plumbers. Call 833-758-6911.",
        '<h2>Water Softener Installation</h2>'
        '<p>Chicago\'s suburban water is hard — loaded with calcium and magnesium that leaves scale on fixtures, spots on dishes, and buildup inside your water heater and pipes. A water softener removes those minerals before they reach your plumbing. We install and service water softeners for homes across Chicagoland.</p>'
        '<h2>Signs You Need a Water Softener</h2>'
        '<ul>'
        '<li><strong>White scale buildup</strong> on faucets, showerheads, and inside kettles</li>'
        '<li><strong>Spots on dishes and glassware</strong> after running the dishwasher</li>'
        '<li><strong>Dry skin and hair</strong> after showering</li>'
        '<li><strong>Stiff, faded laundry</strong> despite using plenty of detergent</li>'
        '<li><strong>Reduced water heater efficiency</strong> from scale buildup on heating elements</li>'
        '<li><strong>Frequent plumbing repairs</strong> due to mineral deposits in valves and fixtures</li>'
        '</ul>'
        '<h2>What Installation Includes</h2>'
        '<ul>'
        '<li>Water hardness testing</li>'
        '<li>Selecting the right unit size for your household</li>'
        '<li>Connecting to the main water supply line</li>'
        '<li>Drain line connection for regeneration</li>'
        '<li>Bypass valve installation for maintenance</li>'
        '<li>Programming and testing</li>'
        '</ul>'
        '<h2>Typical Water Softener Costs</h2>'
        '<ul>'
        '<li><strong>Standard ion-exchange softener:</strong> $1,200–$3,000 including unit and installation</li>'
        '<li><strong>High-capacity or dual-tank:</strong> $2,500–$5,000</li>'
        '<li><strong>Salt-free conditioner:</strong> $1,000–$2,500 (reduces scale but doesn\'t remove minerals)</li>'
        '<li><strong>Ongoing salt costs:</strong> $5–$10/month for standard salt bags</li>'
        '</ul>'
        '<p>A softener extends the life of your water heater, fixtures, and appliances. Most homeowners see savings on soap, detergent, and appliance replacements within a few years.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How hard is Chicago\'s water?</h3>'
        '<p>Chicago city water (from Lake Michigan) is moderately hard at about 8 grains per gallon. Suburban well water can be much harder — 15–25+ grains. We test your water before recommending a unit size.</p>'
        '<h3>Where does the softener get installed?</h3>'
        '<p>Typically near the main water entry point — basement or utility room. It needs access to a drain for regeneration and a power outlet. We also install a bypass valve so you can service the unit without shutting off water to the house.</p>'
        '<h3>Do water softeners waste water?</h3>'
        '<p>They use 40–60 gallons per regeneration cycle (every few days). Modern high-efficiency units use less. The water and appliance savings more than offset the regeneration water use.</p>'
        '<h3>Is softened water safe to drink?</h3>'
        '<p>Yes, though it does add a small amount of sodium. If you\'re on a low-sodium diet, we can install a separate unsoftened line to the kitchen sink or add a reverse osmosis filter for drinking water.</p>'
        '<h3>How long do water softeners last?</h3>'
        '<p>10–15 years with proper maintenance. That means keeping the salt level up, cleaning the brine tank periodically, and replacing the resin bed when it stops softening effectively.</p>'
    )

    svc("water-filter-installation-replacement",
        "Water Filter Installation & Replacement in Chicago, IL",
        "Water filter installation and replacement in Chicago — whole-house, under-sink, and reverse osmosis systems. Call 833-758-6911.",
        '<h2>Water Filter Installation &amp; Replacement</h2>'
        '<p>Whether you want cleaner drinking water, better-tasting water from every tap, or filtration for a specific contaminant, we install and service water filtration systems for homes across Chicagoland. From simple under-sink filters to whole-house systems, we match the right filter to your water quality concerns.</p>'
        '<h2>Types of Water Filters We Install</h2>'
        '<ul>'
        '<li><strong>Under-sink filters:</strong> Carbon block or sediment filters for a single drinking water tap. Most affordable option.</li>'
        '<li><strong>Reverse osmosis (RO):</strong> Multi-stage filtration that removes 95%+ of contaminants. Installs under the kitchen sink with a dedicated faucet.</li>'
        '<li><strong>Whole-house filtration:</strong> Treats all water entering your home — every faucet, shower, and appliance.</li>'
        '<li><strong>UV disinfection:</strong> Kills bacteria and viruses. Used with well water or as an additional safety layer.</li>'
        '<li><strong>Specialty filters:</strong> Lead removal, iron/manganese reduction, chloramine reduction</li>'
        '</ul>'
        '<h2>Typical Water Filter Costs</h2>'
        '<ul>'
        '<li><strong>Under-sink carbon filter:</strong> $150–$400 installed</li>'
        '<li><strong>Reverse osmosis system:</strong> $400–$1,200 installed</li>'
        '<li><strong>Whole-house sediment/carbon filter:</strong> $800–$2,500 installed</li>'
        '<li><strong>Whole-house specialty filtration:</strong> $1,500–$4,000+</li>'
        '<li><strong>Filter replacement (ongoing):</strong> $30–$150/year depending on system type</li>'
        '</ul>'
        '<p>We recommend testing your water first to determine what contaminants you\'re dealing with. That way you invest in filtration that actually addresses your specific water quality issues.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Is Chicago tap water safe to drink?</h3>'
        '<p>Chicago\'s water meets EPA standards, but it does contain chloramine (disinfectant), some lead risk from older service lines, and other trace contaminants. A quality filter adds an extra layer of protection, especially in older homes.</p>'
        '<h3>What\'s the difference between a water softener and a water filter?</h3>'
        '<p>A softener removes hardness minerals (calcium and magnesium). A filter removes contaminants like chlorine, lead, sediment, and bacteria. They address different problems and can be used together.</p>'
        '<h3>How often do filters need to be replaced?</h3>'
        '<p>Carbon filters: every 6–12 months. RO membranes: every 2–3 years. Sediment pre-filters: every 3–6 months. We can set up a replacement schedule and provide the filters.</p>'
        '<h3>Can you install a filter on my refrigerator water line?</h3>'
        '<p>Yes. An inline filter on the refrigerator supply line improves ice and water quality. Simple installation — usually under an hour.</p>'
        '<h3>Do I need a whole-house filter or just under the sink?</h3>'
        '<p>If your concern is drinking water only, an under-sink RO system is the most effective and affordable option. If you want filtered water at every tap and shower (helpful for chloramine removal and skin sensitivity), go whole-house.</p>'
    )

    svc("frozen-broken-pipe-repair",
        "Frozen & Broken Pipe Repair in Chicago, IL",
        "Frozen and broken pipe repair in Chicago — emergency thawing, burst pipe repair, and prevention. 24/7 service. Call 833-758-6911.",
        '<h2>Frozen &amp; Broken Pipe Repair</h2>'
        '<p>Chicago winters are brutal on pipes. When temperatures drop below zero — which happens every year — unprotected water lines freeze, expand, and burst. A single burst pipe can dump hundreds of gallons of water into your home in minutes. We respond to frozen and burst pipe emergencies 24/7 and can have a plumber at your door fast.</p>'
        '<h2>Signs of Frozen Pipes</h2>'
        '<ul>'
        '<li><strong>No water</strong> from a faucet that was working yesterday</li>'
        '<li><strong>Reduced flow</strong> — a trickle instead of full pressure</li>'
        '<li><strong>Frost visible</strong> on exposed pipes in the basement, crawl space, or exterior walls</li>'
        '<li><strong>Unusual sounds</strong> — clanking or banging when you open a tap</li>'
        '<li><strong>Bulging or cracked pipe</strong> — ice has already expanded inside</li>'
        '</ul>'
        '<h2>What We Do</h2>'
        '<ul>'
        '<li><strong>Locate the freeze:</strong> We find exactly where the pipe is frozen using thermal detection and pipe knowledge.</li>'
        '<li><strong>Thaw safely:</strong> Controlled heat application to thaw without causing a burst. Never use open flame.</li>'
        '<li><strong>Repair bursts:</strong> If the pipe has already burst, we isolate the section, cut out the damage, and splice in new pipe.</li>'
        '<li><strong>Prevent future freezing:</strong> Pipe insulation, heat tape, and rerouting recommendations for problem areas.</li>'
        '</ul>'
        '<h2>Typical Frozen/Broken Pipe Repair Costs</h2>'
        '<ul>'
        '<li><strong>Pipe thawing (no burst):</strong> $150–$400</li>'
        '<li><strong>Burst pipe repair (accessible):</strong> $200–$600</li>'
        '<li><strong>Burst pipe repair (in wall or ceiling):</strong> $400–$1,200+ including access and patching</li>'
        '<li><strong>Emergency after-hours response:</strong> Add $100–$200 to above rates</li>'
        '<li><strong>Pipe insulation (preventive):</strong> $100–$500 depending on length and access</li>'
        '</ul>'
        '<p>Water damage from a burst pipe is far more expensive than the pipe repair itself. Act fast and shut off the water main as soon as you notice a burst.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>What should I do if I think my pipes are frozen?</h3>'
        '<p>Open the faucet to relieve pressure. If you can see the frozen section, apply gentle heat — a hair dryer or warm towels. Never use a torch or open flame. If you can\'t find or reach the freeze, call us immediately before it bursts.</p>'
        '<h3>Which pipes freeze first?</h3>'
        '<p>Pipes in exterior walls, unheated crawl spaces, garages, and uninsulated attics freeze first. In Chicago\'s older homes, supply lines running through exterior brick walls are especially vulnerable.</p>'
        '<h3>How can I prevent frozen pipes?</h3>'
        '<p>Insulate exposed pipes, especially in cold areas. Let faucets drip during extreme cold. Keep cabinet doors open under kitchen and bathroom sinks on exterior walls. Maintain heat at 55°F minimum, even if you\'re away.</p>'
        '<h3>Does homeowner\'s insurance cover burst pipe damage?</h3>'
        '<p>Most policies cover sudden water damage from burst pipes, but not the pipe repair itself or damage from gradual leaks. Check your policy and document damage thoroughly with photos.</p>'
        '<h3>Can you repair a pipe without opening the wall?</h3>'
        '<p>If the burst is behind a wall, we need to open access to reach it. We keep the opening as small as possible. For accessible basement or crawl space pipes, no wall work is needed.</p>'
    )

    svc("gas-line-install-repair",
        "Gas Line Installation & Repair in Chicago, IL",
        "Gas line installation and repair in Chicago — stoves, dryers, fireplaces, outdoor grills. Licensed plumbers. Call 833-758-6911.",
        '<h2>Gas Line Installation &amp; Repair</h2>'
        '<p>Gas line work requires a licensed plumber — no exceptions. Whether you\'re hooking up a new gas range, running a line to a fireplace, or dealing with a suspected gas leak, we handle it safely and to code. We install and repair gas lines for homes and businesses throughout Chicagoland.</p>'
        '<h2>Gas Line Services</h2>'
        '<ul>'
        '<li><strong>New gas line runs:</strong> For ranges, dryers, fireplaces, outdoor grills, fire pits, pool heaters</li>'
        '<li><strong>Appliance hookups:</strong> Connecting gas ranges, dryers, and other gas appliances</li>'
        '<li><strong>Gas line repair:</strong> Fixing leaks, corroded fittings, and damaged lines</li>'
        '<li><strong>Gas leak detection:</strong> Electronic leak detection and pressure testing</li>'
        '<li><strong>Gas meter and manifold work:</strong> Upgrading capacity for additional gas appliances</li>'
        '<li><strong>Gas line relocation:</strong> Moving lines for remodels and additions</li>'
        '</ul>'
        '<h2>Gas Leak Warning Signs</h2>'
        '<ul>'
        '<li><strong>Rotten egg smell:</strong> The mercaptan odorant added to natural gas</li>'
        '<li><strong>Hissing sound</strong> near a gas line or appliance</li>'
        '<li><strong>Dead vegetation</strong> in a line above a buried gas line</li>'
        '<li><strong>Higher than normal gas bills</strong> without increased usage</li>'
        '</ul>'
        '<p><strong>If you smell gas, leave the house immediately and call 911 or Peoples Gas at 866-556-6002. Do not flip light switches or use electronics. Call us after the area is cleared for repair.</strong></p>'
        '<h2>Typical Gas Line Costs</h2>'
        '<ul>'
        '<li><strong>Gas appliance hookup (existing line):</strong> $100–$300</li>'
        '<li><strong>New gas line run (10–20 feet):</strong> $300–$800</li>'
        '<li><strong>New gas line run (20–50 feet):</strong> $500–$1,500</li>'
        '<li><strong>Outdoor gas line (grill, fire pit):</strong> $500–$2,000</li>'
        '<li><strong>Gas leak repair:</strong> $200–$600</li>'
        '<li><strong>Gas pressure test:</strong> $100–$250</li>'
        '</ul>'
        '<p>All gas work requires a pressure test and permit inspection. We handle the permit process and coordinate with inspectors.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>Do I need a permit for gas line work in Chicago?</h3>'
        '<p>Yes. All new gas line installations and major repairs require a permit and inspection. We pull the permit and schedule the inspection as part of the job.</p>'
        '<h3>Can you run a gas line to my outdoor grill?</h3>'
        '<p>Yes. We run a dedicated gas line from your meter or manifold to the outdoor cooking area with a shutoff valve. No more propane tanks to refill.</p>'
        '<h3>How do you test for gas leaks?</h3>'
        '<p>We use electronic gas detectors and perform a pressure test on the line. The line is pressurized and monitored for any pressure drop, which indicates a leak. Every new installation and repair gets a pressure test before we turn the gas on.</p>'
        '<h3>Can I convert from electric to gas appliances?</h3>'
        '<p>Yes, as long as your home has a gas supply. We run a new gas line to the appliance location and connect it. Common conversions: electric range to gas, electric dryer to gas, adding a gas fireplace.</p>'
        '<h3>Is it safe to have gas lines in my home?</h3>'
        '<p>Properly installed and maintained gas lines are very safe. Modern black iron and CSST (corrugated stainless steel tubing) piping meets strict safety codes. Regular inspection and prompt repair of any suspected leaks keeps the system safe.</p>'
    )

    svc("sump-pump-install-replacement",
        "Sump Pump Installation & Repair in Chicago, IL",
        "Sump pump installation and repair in Chicago — keep your basement dry. Battery backups, pit installation, and replacements. Call 833-758-6911.",
        '<h2>Sump Pump Installation &amp; Repair</h2>'
        '<p>In Chicagoland, a working sump pump is the difference between a dry basement and thousands of dollars in water damage. Heavy spring rains, high water tables, and clay soil that doesn\'t drain well all put pressure on your foundation. We install, repair, and replace sump pumps and sump pits to keep your basement dry year-round.</p>'
        '<h2>Sump Pump Services</h2>'
        '<ul>'
        '<li><strong>New sump pump installation:</strong> Including pit excavation, pump, check valve, and discharge line</li>'
        '<li><strong>Sump pump replacement:</strong> Swapping a failed or aging pump with a new unit</li>'
        '<li><strong>Battery backup installation:</strong> So your pump runs during power outages (when you need it most)</li>'
        '<li><strong>Sump pit installation:</strong> New pit in a basement that doesn\'t have one</li>'
        '<li><strong>Discharge line repair:</strong> Fixing frozen, clogged, or improperly routed discharge lines</li>'
        '<li><strong>Float switch repair:</strong> When the pump won\'t turn on or won\'t shut off</li>'
        '</ul>'
        '<h2>Signs Your Sump Pump Needs Attention</h2>'
        '<ul>'
        '<li><strong>Pump runs constantly</strong> — even when it\'s not raining</li>'
        '<li><strong>Pump doesn\'t turn on</strong> — failed float switch or motor</li>'
        '<li><strong>Strange noises</strong> — grinding, rattling, or humming without pumping</li>'
        '<li><strong>Water in the basement</strong> despite having a pump</li>'
        '<li><strong>Pump is 7+ years old</strong> — approaching end of typical lifespan</li>'
        '</ul>'
        '<h2>Typical Sump Pump Costs</h2>'
        '<ul>'
        '<li><strong>Sump pump replacement (standard 1/3 HP):</strong> $400–$800 installed</li>'
        '<li><strong>Sump pump replacement (heavy-duty 1/2 HP):</strong> $600–$1,200 installed</li>'
        '<li><strong>New sump pit + pump installation:</strong> $1,500–$3,500</li>'
        '<li><strong>Battery backup system:</strong> $500–$1,500 installed</li>'
        '<li><strong>Discharge line repair/reroute:</strong> $200–$600</li>'
        '</ul>'
        '<p>Don\'t wait until the pump fails during a storm. If your pump is over 7 years old or making unusual noises, proactive replacement is much cheaper than water damage cleanup.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long do sump pumps last?</h3>'
        '<p>5–10 years for standard pumps. Heavy-duty cast iron pumps can last longer. Battery backups typically last 3–5 years before the battery needs replacement. We recommend replacing primary pumps at the 7-year mark as preventive maintenance.</p>'
        '<h3>Do I need a battery backup sump pump?</h3>'
        '<p>In Chicago, absolutely. Power outages during severe storms are common — exactly when your pump needs to run. A battery backup keeps pumping for 6–12 hours without power. It\'s one of the best investments for basement protection.</p>'
        '<h3>Why does my sump pump run so often?</h3>'
        '<p>A high water table, underground springs, or poor drainage around the foundation can cause frequent cycling. This is normal in many Chicago neighborhoods. If the pump is cycling every few minutes, consider upgrading to a higher-capacity pump.</p>'
        '<h3>Where should the discharge line go?</h3>'
        '<p>The discharge must route water away from your foundation — at least 10 feet, or to a storm drain if your municipality allows it. In Chicago, discharging to the sanitary sewer is prohibited. We make sure the discharge is properly routed and freeze-protected.</p>'
        '<h3>Can you install a sump pump in a basement that doesn\'t have a pit?</h3>'
        '<p>Yes. We cut a section of the concrete floor, excavate a pit, install a liner and cover, set the pump, and run the discharge line. It\'s a common job in older Chicago homes that were built without drainage systems.</p>'
    )

    svc("sump-pump-battery-backup-install",
        "Sump Pump Battery Backup in Chicago, IL",
        "Sump pump battery backup installation in Chicago — protect your basement during power outages. Licensed plumbers. Call 833-758-6911.",
        '<h2>Sump Pump Battery Backup</h2>'
        '<p>Your sump pump is useless without power. And power outages in Chicago happen most often during severe storms — exactly when water is pouring into your sump pit the fastest. A battery backup sump pump kicks in automatically when the power goes out, keeping your basement dry when your primary pump can\'t run.</p>'
        '<h2>How Battery Backup Pumps Work</h2>'
        '<p>A battery backup system is a second pump installed alongside your primary sump pump, powered by a deep-cycle marine battery or a dedicated battery pack. When the power goes out (or your primary pump fails), the backup pump activates automatically. Most systems can pump 2,000–3,000 gallons on a full charge — enough for 6–12 hours of protection.</p>'
        '<h2>Types of Backup Systems</h2>'
        '<ul>'
        '<li><strong>Battery-powered backup pump:</strong> Dedicated pump with a 12V deep-cycle battery. Most common and reliable option.</li>'
        '<li><strong>Water-powered backup pump:</strong> Uses municipal water pressure to pump — no battery needed, but uses water and requires adequate pressure.</li>'
        '<li><strong>Combination primary + backup:</strong> Integrated systems with built-in battery backup.</li>'
        '</ul>'
        '<h2>Typical Battery Backup Costs</h2>'
        '<ul>'
        '<li><strong>Battery backup system (installed):</strong> $500–$1,500</li>'
        '<li><strong>Water-powered backup (installed):</strong> $400–$1,000</li>'
        '<li><strong>Battery replacement (every 3–5 years):</strong> $100–$250</li>'
        '<li><strong>Combination primary + backup system:</strong> $1,000–$2,500 installed</li>'
        '</ul>'
        '<p>Compare these costs to a flooded basement — water damage restoration runs $5,000–$25,000+. A battery backup is inexpensive insurance.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How long will the battery backup run during an outage?</h3>'
        '<p>6–12 hours of continuous pumping with a fully charged battery, depending on water volume and pump frequency. A maintenance charger keeps the battery at full charge between outages.</p>'
        '<h3>Do I still need a battery backup if I have a generator?</h3>'
        '<p>Generators are great but they don\'t start instantly. There\'s a gap between power loss and generator startup. Also, generators can fail. A battery backup provides instant, automatic protection as a secondary safety net.</p>'
        '<h3>How often should the battery be replaced?</h3>'
        '<p>Every 3–5 years for standard deep-cycle batteries. Some premium systems have longer-lasting batteries. We test the battery during annual maintenance visits and recommend replacement when capacity drops.</p>'
        '<h3>Can a battery backup be added to my existing sump pump?</h3>'
        '<p>Yes. We install the backup pump and battery alongside your existing primary pump in the same pit. No need to replace your current pump — the backup works as a companion system.</p>'
        '<h3>Will the battery backup alert me if it activates?</h3>'
        '<p>Most modern systems have an audible alarm that sounds when the backup activates, when the battery is low, or when there\'s a pump failure. Some premium units offer Wi-Fi alerts to your phone.</p>'
    )

    svc("water-leak-detection-repair",
        "Water Leak Detection & Repair in Chicago, IL",
        "Water leak detection and repair in Chicago — hidden leaks found and fixed fast. Slab leaks, pipe leaks, fixture leaks. Call 833-758-6911.",
        '<h2>Water Leak Detection &amp; Repair</h2>'
        '<p>A water leak you can\'t see can do more damage than one you can. Hidden leaks inside walls, under slabs, and in crawl spaces waste water, promote mold growth, and can cause serious structural damage before you notice. We use electronic leak detection equipment to find hidden leaks without tearing your home apart, then make the repair.</p>'
        '<h2>Signs of a Hidden Water Leak</h2>'
        '<ul>'
        '<li><strong>Unexplained high water bills</strong> — a sudden spike with no change in usage</li>'
        '<li><strong>Water meter spinning</strong> when all fixtures are off</li>'
        '<li><strong>Damp or discolored spots</strong> on walls, ceilings, or floors</li>'
        '<li><strong>Musty smell</strong> — hidden moisture promotes mold and mildew</li>'
        '<li><strong>Sound of running water</strong> when nothing is on</li>'
        '<li><strong>Warm spot on the floor</strong> — possible hot water slab leak</li>'
        '<li><strong>Foundation cracks</strong> — water erosion under the slab</li>'
        '</ul>'
        '<h2>How We Find Leaks</h2>'
        '<ul>'
        '<li><strong>Electronic leak detection:</strong> Acoustic sensors that amplify the sound of water escaping a pipe, pinpointing the location through walls and slabs.</li>'
        '<li><strong>Thermal imaging:</strong> Infrared cameras that detect temperature differences caused by moisture behind walls or under floors.</li>'
        '<li><strong>Pressure testing:</strong> Isolating sections of the plumbing system to narrow down the leak location.</li>'
        '<li><strong>Camera inspection:</strong> For drain and sewer leaks, a pipe camera shows the exact location and cause.</li>'
        '</ul>'
        '<h2>Typical Leak Detection and Repair Costs</h2>'
        '<ul>'
        '<li><strong>Leak detection service:</strong> $150–$500 depending on complexity</li>'
        '<li><strong>Accessible pipe repair (exposed):</strong> $150–$400</li>'
        '<li><strong>In-wall pipe repair:</strong> $300–$800+ including wall access and patching</li>'
        '<li><strong>Slab leak repair (reroute):</strong> $1,500–$4,000</li>'
        '<li><strong>Slab leak repair (direct access):</strong> $1,000–$3,000 including concrete cutting and restoration</li>'
        '</ul>'
        '<p>Early detection saves money. A small leak left unfound for months can cause thousands in water damage, mold remediation, and structural repair.</p>'
        '<h2>Frequently Asked Questions</h2>'
        '<h3>How do I know if I have a slab leak?</h3>'
        '<p>Warm or wet spots on the floor, the sound of water running under the slab, sudden increases in water bills, and cracks in the foundation are all signs. A slab leak can also cause low water pressure if it\'s on a supply line.</p>'
        '<h3>Can you find a leak without tearing up my house?</h3>'
        '<p>Yes. Our electronic detection equipment locates leaks through walls, floors, and concrete without destructive exploration. We only open up exactly where the leak is — no guesswork.</p>'
        '<h3>What causes hidden pipe leaks?</h3>'
        '<p>Corrosion (especially in older galvanized and copper pipes), high water pressure, freeze damage, settling foundations, and poor original installation. In Chicago, temperature extremes accelerate pipe wear.</p>'
        '<h3>Is a slab leak covered by insurance?</h3>'
        '<p>Most homeowner policies cover the resulting water damage but not the cost of finding or repairing the leak itself. Some policies also don\'t cover damage from gradual leaks. Check your policy and document everything.</p>'
        '<h3>Should I reroute the pipe or repair in place?</h3>'
        '<p>For slab leaks, rerouting through the ceiling or walls is often more cost-effective and less disruptive than breaking through the slab. For accessible leaks, direct repair is usually simpler and cheaper. We\'ll recommend the best approach for your situation.</p>'
    )
